"""seed data

Revision ID: cc1ad206a770
Revises: e33e15a32fcd
Create Date: 2023-10-02 23:26:07.940872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.product import Product
from models.inventory import Inventory
from models.sales import Sale
from models.historicalinventory import HistoricalInventory
from seeders.product_seed import products_seed_data
from seeders.sales_seed import sales_seed_data
from seeders.inventory_seed import inventory_seed_data
from seeders.historical_inventory_seed import historical_inventory_seed_data



# revision identifiers, used by Alembic.
revision: str = 'cc1ad206a770'
down_revision: Union[str, None] = 'e33e15a32fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     # Create a connection to the database
    connection = op.get_bind()
    
    # Insert seed data for product
    for data in products_seed_data:
        insert_statement = sa.text(
            "INSERT INTO products (name, description, price, category) "
            "VALUES (:name, :description, :price, :category)"
        )
        connection.execute(insert_statement, **data)
        
    # Insert seed data for sales
    # for data in sales_seed_data:
    #     new_record = Sale(**data)
    #     connection.execute(sa.insert(Sale).values(**new_record.__dict__))
        
    # Insert seed data for inventory
    # for data in inventory_seed_data:
    #     new_record = Inventory(**data)
    #     connection.execute(sa.insert(Inventory).values(**new_record.__dict__))
        
    # Insert seed data for historical_inventory
    # for data in historical_inventory_seed_data:
    #     new_record = HistoricalInventory(**data)
    #     connection.execute(sa.insert(HistoricalInventory).values(**new_record.__dict__))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
