sales_seed_data = [
    {
        "id": 1,
        "product_id": 1,
        "quantity_sold": 10,
        "sale_amount": 5999.90,
        "sale_date": "2023-09-01",
        "category": "Electronics",
    },
    {
        "id": 2,
        "product_id": 2,
        "quantity_sold": 5,
        "sale_amount": 4999.95,
        "sale_date": "2023-09-02",
        "category": "Electronics",
    },
    {
        "id": 3,
        "product_id": 3,
        "quantity_sold": 8,
        "sale_amount": 2399.92,
        "sale_date": "2023-09-03",
        "category": "Electronics",
    },
    {
        "id": 4,
        "product_id": 4,
        "quantity_sold": 15,
        "sale_amount": 1199.85,
        "sale_date": "2023-09-01",
        "category": "Footwear",
    },
    {
        "id": 5,
        "product_id": 5,
        "quantity_sold": 20,
        "sale_amount": 399.80,
        "sale_date": "2023-09-02",
        "category": "Apparel",
    },
    {
        "id": 6,
        "product_id": 1,
        "quantity_sold": 12,
        "sale_amount": 7199.88,
        "sale_date": "2023-09-04",
        "category": "Electronics",
    },
    {
        "id": 7,
        "product_id": 2,
        "quantity_sold": 6,
        "sale_amount": 5999.70,
        "sale_date": "2023-09-05",
        "category": "Electronics",
    },
    {
        "id": 8,
        "product_id": 4,
        "quantity_sold": 20,
        "sale_amount": 1599.80,
        "sale_date": "2023-09-04",
        "category": "Footwear",
    },
    {
        "id": 9,
        "product_id": 5,
        "quantity_sold": 15,
        "sale_amount": 299.85,
        "sale_date": "2023-09-05",
        "category": "Apparel",
    },
    {
        "id": 10,
        "product_id": 1,
        "quantity_sold": 8,
        "sale_amount": 4799.92,
        "sale_date": "2023-09-06",
        "category": "Electronics",
    },
    {
        "id": 11,
        "product_id": 3,
        "quantity_sold": 10,
        "sale_amount": 4799.90,
        "sale_date": "2023-09-06",
        "category": "Electronics",
    },
    {
        "id": 12,
        "product_id": 4,
        "quantity_sold": 12,
        "sale_amount": 959.88,
        "sale_date": "2023-09-07",
        "category": "Footwear",
    },
    {
        "id": 13,
        "product_id": 5,
        "quantity_sold": 18,
        "sale_amount": 359.82,
        "sale_date": "2023-09-07",
        "category": "Apparel",
    },
    {
        "id": 14,
        "product_id": 1,
        "quantity_sold": 7,
        "sale_amount": 4199.93,
        "sale_date": "2023-09-08",
        "category": "Electronics",
    },
    {
        "id": 15,
        "product_id": 2,
        "quantity_sold": 4,
        "sale_amount": 3999.96,
        "sale_date": "2023-09-08",
        "category": "Electronics",
    },
    {
        "id": 16,
        "product_id": 4,
        "quantity_sold": 10,
        "sale_amount": 799.90,
        "sale_date": "2023-09-09",
        "category": "Footwear",
    },
    {
        "id": 17,
        "product_id": 5,
        "quantity_sold": 12,
        "sale_amount": 239.88,
        "sale_date": "2023-09-09",
        "category": "Apparel",
    },
    {
        "id": 18,
        "product_id": 1,
        "quantity_sold": 9,
        "sale_amount": 5399.91,
        "sale_date": "2023-09-10",
        "category": "Electronics",
    },
    {
        "id": 19,
        "product_id": 3,
        "quantity_sold": 11,
        "sale_amount": 2639.91,
        "sale_date": "2023-09-10",
        "category": "Electronics",
    },
    {
        "id": 20,
        "product_id": 4,
        "quantity_sold": 8,
        "sale_amount": 639.92,
        "sale_date": "2023-09-11",
        "category": "Footwear",
    },
    {
        "id": 21,
        "product_id": 5,
        "quantity_sold": 16,
        "sale_amount": 319.84,
        "sale_date": "2023-09-11",
        "category": "Apparel",
    },
    {
        "id": 22,
        "product_id": 1,
        "quantity_sold": 11,
        "sale_amount": 6599.89,
        "sale_date": "2023-09-12",
        "category": "Electronics",
    },
    {
        "id": 23,
        "product_id": 2,
        "quantity_sold": 7,
        "sale_amount": 6999.93,
        "sale_date": "2023-09-12",
        "category": "Electronics",
    },
    {
        "id": 24,
        "product_id": 3,
        "quantity_sold": 9,
        "sale_amount": 5399.91,
        "sale_date": "2023-09-13",
        "category": "Electronics",
    },
    {
        "id": 25,
        "product_id": 4,
        "quantity_sold": 14,
        "sale_amount": 1119.86,
        "sale_date": "2023-09-13",
        "category": "Footwear",
    },
    {
        "id": 26,
        "product_id": 5,
        "quantity_sold": 19,
        "sale_amount": 379.81,
        "sale_date": "2023-09-14",
        "category": "Apparel",
    },
    {
        "id": 27,
        "product_id": 1,
        "quantity_sold": 13,
        "sale_amount": 7699.87,
        "sale_date": "2023-09-14",
        "category": "Electronics",
    },
    {
        "id": 28,
        "product_id": 2,
        "quantity_sold": 8,
        "sale_amount": 7999.92,
        "sale_date": "2023-09-15",
        "category": "Electronics",
    },
    {
        "id": 29,
        "product_id": 4,
        "quantity_sold": 18,
        "sale_amount": 1439.82,
        "sale_date": "2023-09-15",
        "category": "Footwear",
    },
    {
        "id": 30,
        "product_id": 5,
        "quantity_sold": 14,
        "sale_amount": 279.86,
        "sale_date": "2023-09-16",
        "category": "Apparel",
    },
    {
        "id": 31,
        "product_id": 1,
        "quantity_sold": 14,
        "sale_amount": 8399.86,
        "sale_date": "2023-09-16",
        "category": "Electronics",
    },
    {
        "id": 32,
        "product_id": 2,
        "quantity_sold": 9,
        "sale_amount": 8999.91,
        "sale_date": "2023-09-17",
        "category": "Electronics",
    },
    {
        "id": 33,
        "product_id": 3,
        "quantity_sold": 12,
        "sale_amount": 5759.88,
        "sale_date": "2023-09-17",
        "category": "Electronics",
    },
    {
        "id": 34,
        "product_id": 4,
        "quantity_sold": 20,
        "sale_amount": 1599.80,
        "sale_date": "2023-09-18",
        "category": "Footwear",
    },
    {
        "id": 35,
        "product_id": 5,
        "quantity_sold": 15,
        "sale_amount": 299.85,
        "sale_date": "2023-09-18",
        "category": "Apparel",
    },
    {
        "id": 36,
        "product_id": 1,
        "quantity_sold": 10,
        "sale_amount": 5999.90,
        "sale_date": "2023-09-19",
        "category": "Electronics",
    },
    {
        "id": 37,
        "product_id": 2,
        "quantity_sold": 5,
        "sale_amount": 4999.95,
        "sale_date": "2023-09-19",
        "category": "Electronics",
    },
    {
        "id": 38,
        "product_id": 3,
        "quantity_sold": 8,
        "sale_amount": 2399.92,
        "sale_date": "2023-09-20",
        "category": "Electronics",
    },
    {
        "id": 39,
        "product_id": 4,
        "quantity_sold": 15,
        "sale_amount": 1199.85,
        "sale_date": "2023-09-20",
        "category": "Footwear",
    },
    {
        "id": 40,
        "product_id": 5,
        "quantity_sold": 20,
        "sale_amount": 399.80,
        "sale_date": "2023-09-21",
        "category": "Apparel",
    },
    {
        "id": 41,
        "product_id": 1,
        "quantity_sold": 12,
        "sale_amount": 7199.88,
        "sale_date": "2023-09-21",
        "category": "Electronics",
    },
    {
        "id": 42,
        "product_id": 2,
        "quantity_sold": 6,
        "sale_amount": 5999.70,
        "sale_date": "2023-09-22",
        "category": "Electronics",
    },
    {
        "id": 43,
        "product_id": 4,
        "quantity_sold": 20,
        "sale_amount": 1599.80,
        "sale_date": "2023-09-22",
        "category": "Footwear",
    },
    {
        "id": 44,
        "product_id": 5,
        "quantity_sold": 15,
        "sale_amount": 299.85,
        "sale_date": "2023-09-23",
        "category": "Apparel",
    },
    {
        "id": 45,
        "product_id": 1,
        "quantity_sold": 8,
        "sale_amount": 4799.92,
        "sale_date": "2023-09-23",
        "category": "Electronics",
    },
    {
        "id": 46,
        "product_id": 3,
        "quantity_sold": 10,
        "sale_amount": 4799.90,
        "sale_date": "2023-09-24",
        "category": "Electronics",
    },
    {
        "id": 47,
        "product_id": 4,
        "quantity_sold": 12,
        "sale_amount": 959.88,
        "sale_date": "2023-09-24",
        "category": "Footwear",
    },
    {
        "id": 48,
        "product_id": 5,
        "quantity_sold": 18,
        "sale_amount": 359.82,
        "sale_date": "2023-09-25",
        "category": "Apparel",
    },
    {
        "id": 49,
        "product_id": 1,
        "quantity_sold": 7,
        "sale_amount": 4199.93,
        "sale_date": "2023-09-25",
        "category": "Electronics",
    },
    {
        "id": 50,
        "product_id": 2,
        "quantity_sold": 4,
        "sale_amount": 3999.96,
        "sale_date": "2023-09-26",
        "category": "Electronics",
    },
]